### ISSUE TITLE
cannot build capnp

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/builder#1]
```
set -ex
cd /tmp
curl -O https://capnproto.org/capnproto-c++-0.5.3.tar.gz
tar zxf capnproto-c++-0.5.3.tar.gz
cd capnproto-c++-0.5.3
./configure
make -j6 check
sudo make install
```

**Comment by rkhamis** [comment]
moved to https://github.com/Jumpscale/ays_build/issues/16

**Comment by despiegk** [comment]
I also tried with https://hub.docker.com/r/frolvlad/alpine-glibc/
no luck

**Comment by despiegk** [comment]
![image](https://cloud.githubusercontent.com/assets/6021844/24853059/03c3436a-1dda-11e7-9868-f413c9b1e211.png)

**Comment by despiegk** [comment]
fixed
